### ISSUE TITLE
将这个添加在tableview的tableHeaderView，初始有问题

### ISSUE THREAD

**Issue by Alamoalone** [xxxIxxxx/XXXCardStore#1]
你好，我最近做项目时，看到大佬做的这个就拿去用了，但是遇到一如题，初始会只显示一张，下面看不到剩余张数，只有滑动了一张才会显示正常，我因为解决不了，特向大佬请教
![11543990297_ pic](https://user-images.githubusercontent.com/13886204/49493620-c09c0280-f897-11e8-90c1-35a3489df139.jpg)---->
![21543990319_ pic](https://user-images.githubusercontent.com/13886204/49493640-d01b4b80-f897-11e8-865e-133f27e3df1a.jpg)
这是我在项目中的写法
<img width="878" alt="wechatdaf5ea5014cd811e34fbed8b709b89db" src="https://user-images.githubusercontent.com/13886204/49493660-e1645800-f897-11e8-8a1b-5f3e46d2ff98.png">
<img width="1194" alt="wechatbe158ed96af4c4328cf804a67b30dce9" src="https://user-images.githubusercontent.com/13886204/49493678-ee814700-f897-11e8-846f-474e871382cd.png">

**Comment by xxxIxxxx** [comment]
@Alamoalone 自定义view 的赋值操作  需要在代理里边实现

**Comment by Alamoalone** [comment]
@xxxIxxxx 自定义我有在代理中做，如下图
![image](https://user-images.githubusercontent.com/13886204/49497699-05c63180-f8a4-11e8-997e-3ca2becd5312.png)

**Comment by xxxIxxxx** [comment]
@Alamoalone 可能你自定义view里边实现有问题，我现在在外边 方便的话 发一下Demo到我邮箱 i2yf@foxmail.com

**Comment by Alamoalone** [comment]
@xxxIxxxx 发给你了
![image](https://user-images.githubusercontent.com/13886204/49499458-11682700-f8a9-11e8-910e-db2bd1aa354b.png)

**Comment by xxxIxxxx** [comment]
@Alamoalone      在调用 [self.cardView reloadData]; 之后 再调用一次

```
- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = [UIColor whiteColor];
    [self setNavGationView];
    
    self.activityTableView.tableHeaderView = self.cardView;
    [self.cardView reloadData];
    [self.cardView reloadData];
    [self.view addSubview:self.activityTableView];
}

```

另外加上这句,防止卡片停留在window

```
- (void)viewDidDisappear:(BOOL)animated {
    [super viewDidDisappear:animated];
    [self.cardView resetCardView];
}

```

**Comment by Alamoalone** [comment]
@xxxIxxxx正常了，感谢感谢
![unadjustednonraw_thumb_dd](https://user-images.githubusercontent.com/13886204/49505178-28f9dc80-f8b6-11e8-8d27-a25283f90114.jpg)
